In [1]:
# -*- coding: utf-8 -*-

# coding: utf-8
from Datos import Datos


Notebook para probar la clase **Datos**. Esta clase procesa los datos de un fichero dado para que podamos trabajar con ellos.


Realizamos la prueba con dos ficheros:
    

El programa debe hacer una lista de valores booleanos que indican si los valores procesados son **nominales**.

In [2]:
   
    tictac = Datos("tic-tac-toe.data")
    german = Datos("german.data")
    print("Tic-tac-toe:\n")
    print("nominalAtributos:")
    print(tictac.nominalAtributos)

Tic-tac-toe:

nominalAtributos:
[True, True, True, True, True, True, True, True, True, True]


El programa asigna valores numéricos a los nominales para poder trabajar con ellos y lo guarda en un **diccionario**.

In [3]:
    print("\nDiccionario:")
    print(tictac.diccionario)


Diccionario:
{'TLeftSq': {'b': 0, 'o': 1, 'x': 2}, 'TMidSq': {'b': 0, 'o': 1, 'x': 2}, 'TRightSq': {'b': 0, 'o': 1, 'x': 2}, 'MLeftSq': {'b': 0, 'o': 1, 'x': 2}, 'MMidSq': {'b': 0, 'o': 1, 'x': 2}, 'MRightSq': {'b': 0, 'o': 1, 'x': 2}, 'BLeftSq': {'b': 0, 'o': 1, 'x': 2}, 'BMidSq': {'b': 0, 'o': 1, 'x': 2}, 'BRightSq': {'b': 0, 'o': 1, 'x': 2}, 'Class': {'negative': 0, 'positive': 1}}


Array **numpy** que almacena los datos con los que trabajaremos.

In [4]:
    print("\nDatos:")
    print(tictac.datos)
    


Datos:
[[2 2 2 ... 1 1 1]
 [2 2 2 ... 2 1 1]
 [2 2 2 ... 1 2 1]
 ...
 [1 2 1 ... 1 2 0]
 [1 2 1 ... 1 2 0]
 [1 1 2 ... 2 2 0]]


El programa debe hacer una lista de valores booleanos que indican si los valores procesados son **nominales**.

In [5]:
    print("German:\n")
    print("nominalAtributos:")
    print(german.nominalAtributos)

German:

nominalAtributos:
[True, False, True, True, False, True, True, False, True, True, False, True, False, True, True, False, True, False, True, True, False]


El programa asigna valores numéricos a los nominales para poder trabajar con ellos y lo guarda en un **diccionario**.

In [6]:
    print("\nDiccionario:")
    print(german.diccionario)


Diccionario:
{'A1': {'A11': 0, 'A12': 1, 'A13': 2, 'A14': 3}, 'A2': {}, 'A3': {'A30': 0, 'A31': 1, 'A32': 2, 'A33': 3, 'A34': 4}, 'A4': {'A40': 0, 'A41': 1, 'A410': 2, 'A42': 3, 'A43': 4, 'A44': 5, 'A45': 6, 'A46': 7, 'A48': 8, 'A49': 9}, 'A5': {}, 'A6': {'A61': 0, 'A62': 1, 'A63': 2, 'A64': 3, 'A65': 4}, 'A7': {'A71': 0, 'A72': 1, 'A73': 2, 'A74': 3, 'A75': 4}, 'A8': {}, 'A9': {'A91': 0, 'A92': 1, 'A93': 2, 'A94': 3}, 'A10': {'A101': 0, 'A102': 1, 'A103': 2}, 'A11': {}, 'A12': {'A121': 0, 'A122': 1, 'A123': 2, 'A124': 3}, 'A13': {}, 'A14': {'A141': 0, 'A142': 1, 'A143': 2}, 'A15': {'A151': 0, 'A152': 1, 'A153': 2}, 'A16': {}, 'A17': {'A171': 0, 'A172': 1, 'A173': 2, 'A174': 3}, 'A18': {}, 'A19': {'A191': 0, 'A192': 1}, 'A20': {'A201': 0, 'A202': 1}, 'Class': {}}


Array **numpy** que almacena los datos con los que trabajaremos.

In [7]:
    print("\nDatos:")
    print(german.datos)


Datos:
[[ 0  6  4 ...  1  0  1]
 [ 1 48  2 ...  0  0  2]
 [ 3 12  4 ...  0  0  1]
 ...
 [ 3 12  2 ...  0  0  1]
 [ 0 45  2 ...  1  0  2]
 [ 1 45  4 ...  0  0  1]]
